// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.SP;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace API.Context.SP
{
    public partial interface ISPContextProcedures
    {
        Task<List<uspUserAddResult>> uspUserAddAsync(string FullName, string PhoneNumber, string UserName, string Email, string Password, bool? Active, string KTP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspUserGetResult>> uspUserGetAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspUserLoginResult>> uspUserLoginAsync(string Username, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspUserUpdateAsync(int? ID, string FullName, string PhoneNumber, string UserName, string Email, string Password, bool? Active, string KTP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
