// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Context.SP
{
    public partial class uspGetPermissionListResult
    {
        public string Name { get; set; }
        public int ID { get; set; }
        public bool? IsSelected { get; set; }
    }
}
