// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Context.SP
{
    public partial class uspUserAddResult
    {
        [Column("ID", TypeName = "decimal(38,0)")]
        public decimal? ID { get; set; }
    }
}
