// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Debt
{
    public int ID { get; set; }

    public int? CustomerID { get; set; }

    public decimal Amount { get; set; }

    public DateTime DueDate { get; set; }

    public short? StatusID { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }
}