// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Debt
{
    public int ID { get; set; }

    public DateTime DueDate { get; set; }

    public decimal AmountPaid { get; set; }

    public DateTime PaymentDate { get; set; }
}