// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Lookup
{
    public int ID { get; set; }

    public string Entity { get; set; }

    public short Key { get; set; }

    public string Name { get; set; }
}