// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class PurchaseOrderItem
{
    public int ID { get; set; }

    public int? PurchaseOrderID { get; set; }

    public int? ProductID { get; set; }

    public int OrderedQuantity { get; set; }

    public int? ReceivedQuantity { get; set; }
}