// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class PurchaseOrder
{
    public int ID { get; set; }

    public short SupplierID { get; set; }

    public DateTime Date { get; set; }

    public short StatusID { get; set; }
}