// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class RolePermission
{
    public int ID { get; set; }

    public int PermissionID { get; set; }

    public int RoleID { get; set; }
}