// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Supplier
{
    public int ID { get; set; }

    public string Name { get; set; }

    public string ContactPerson { get; set; }

    public int ContactNumber { get; set; }
}