// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Trade
{
    public int ID { get; set; }

    public DateTime Date { get; set; }

    public string No { get; set; }

    public int? CustomerID { get; set; }

    public short TradeType { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedBy { get; set; }

    public string CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public short? DebtID { get; set; }

    public short? StatusID { get; set; }

    public string Note { get; set; }
}