// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class User
{
    public int ID { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool Active { get; set; }

    public string KTP { get; set; }
}