// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class RoleClaim
{
    public int ID { get; set; }

    public int RoleID { get; set; }

    public string ClaimType { get; set; }

    public string ClaimValue { get; set; }
}